# Generated by Django 5.1.2 on 2024-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.DateTimeField(auto_now_add=True, verbose_name='Когда было совершено')),
                ('code_log', models.PositiveSmallIntegerField(choices=[(0, 'Блокировки'), (1, 'Роли'), (2, 'Товары'), (3, 'Блоги'), (4, 'Удаление пользователя')], verbose_name='Код лога')),
                ('log_info', models.CharField(max_length=1024, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='BanCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_date', models.DateTimeField(auto_now_add=True, verbose_name='Когда забанели')),
                ('ban_time', models.DurationField(null=True, verbose_name='Время бана')),
            ],
            options={
                'verbose_name': 'Блокировка общения',
                'verbose_name_plural': 'Блокировки общения',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status_order', models.PositiveSmallIntegerField(choices=[(0, 'Доставляется'), (1, 'Доставлено'), (2, 'Отменено')], default=0, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('message', models.TextField(max_length=4096, verbose_name='Сообщение')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Отображается'), (1, 'Удалено')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Сообщение заказа',
                'verbose_name_plural': 'Сообщения заказов',
            },
        ),
    ]
