# Generated by Django 5.1.2 on 2024-11-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bancommunication',
            name='got_banned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='got_banned_fk', to=settings.AUTH_USER_MODEL, verbose_name='Забаненный'),
        ),
        migrations.AddField(
            model_name='bancommunication',
            name='who_banned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_banned_fk', to=settings.AUTH_USER_MODEL, verbose_name='Кто забанил'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_order_fk', to='pharmacy.goods', verbose_name='Товар заказа'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fk', to='employee.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_reply', to='employee.ordermessage', verbose_name='Ответ на сообщение'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='wrote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_wrote', to=settings.AUTH_USER_MODEL, verbose_name='Написал'),
        ),
    ]
