# Generated by Django 5.1.2 on 2024-11-07 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('message', models.TextField(max_length=4096, verbose_name='Сообщение')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Отображается'), (1, 'Удалено')], default=0, verbose_name='Статус')),
                ('it_read', models.BooleanField(default=False)),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_PM_fk', to=settings.AUTH_USER_MODEL, verbose_name='Кто получил')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_reply', to='user.privatemessage', verbose_name='Ответ на сообщение')),
                ('wrote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_wrote', to=settings.AUTH_USER_MODEL, verbose_name='Написал')),
            ],
            options={
                'verbose_name': 'Личное сообщение',
                'verbose_name_plural': 'Личные сообщения',
            },
        ),
    ]
