# Generated by Django 5.1.2 on 2024-11-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='it_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
