# Generated by Django 5.1.2 on 2024-11-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='user_notify',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify_fk', to=settings.AUTH_USER_MODEL, verbose_name='Уведомляемый пользователь'),
        ),
    ]
